### ISSUE TITLE
Support for Bevy 0.9

### ISSUE THREAD

**Issue by Dessix** [LiamGallagher737/bevy_mod_gizmos#16]
[Bevy 0.9 has been released](https://bevyengine.org/news/bevy-0-9/); this package is hard-locked to `0.8`, in its current `Cargo.toml`, and `0.7` in [its most recent crates.io release](https://crates.io/crates/bevy_mod_gizmos/0.1.1).

There are likely many remaining extensions lacking 0.9 support, perhaps a `bevy-0.9` flag or a more-open requirements specification would be in order, to allow them to upgrade smoothly?

**Comment by LiamGallagher737** [comment]
https://github.com/LiamGallagher737/bevy_mod_gizmos/commit/7359847ee753b293f47fa376e5de20c01db1100c should now be working with bevy 0.9
